### ISSUE TITLE
need to turn on mathjax for the book

### ISSUE THREAD

**Issue by eeholmes** [PACEHackWeek/pace-2024#38]
@itcarroll The ml notebook has math but looks like mathjax has not been added as an extension. I'll look into it later. The ML talk is not until Thursday.

**Comment by eeholmes** [comment]
hmm, dollarmath myst extension is enabled. `$ $` should be working

**Comment by eeholmes** [comment]
meh https://github.com/jupyter-book/jupyter-book/issues/1705

**Comment by itcarroll** [comment]
Because we don't use MyST markdown in the notebooks, The third argument to the custom nb reader causes it to use commonmark. Could be related?

**Comment by eeholmes** [comment]
Math works fine in the original jupyterbook-template:
https://eeholmes.github.io/jupyterbook-template/tutorials/example/tutorial-notebook.html#math

I don't see what we changed.  Is there a setting that was used in the notebooks to 'turn-off' myst? Seems unlikely since other stuff works.

**Comment by eeholmes** [comment]
"The third argument to the custom nb reader causes it to use commonmark." where is this? Is this a change that is different for our book?

**Comment by eeholmes** [comment]
Here is an example. this math.ipynb works fine in the original juptyerbook-template
https://eeholmes.github.io/jupyterbook-template/tutorials/example/math.html

but not in ours. So we changed something in the config to make math stop working.
https://deploy-preview-39--pace-2024.netlify.app/presentations/hackweek/math

**Comment by eeholmes** [comment]
Ok, something to fix for after the hackweek. I tried the only thing that seemed likely, aka that we do not execute the ipynb but that does not change things. And it is not from jupytext since I didn't use that for math.ipynb.

**Comment by itcarroll** [comment]
> "The third argument to the custom nb reader causes it to use commonmark." where is this? Is this a change that is different for our book?

Sorry, I was posting from my phone.

[Here is the line](https://github.com/PACEHackWeek/pace-2024/blob/206263306be66b72dc0f513538ad4e23402000ea/book/_config.yml#L63) that switches rendering of ipynb markdown cells to commonmark. Math should work in commonmark though. Worth flipping to `false` to find out.

**Comment by itcarroll** [comment]
fixed by d536e1c
